Repository matthiasbeyer/imag, pull requests merged in 2018-02, with the labels that each got.

#1272 Prepare 0.6.0 release
  bin/domain/imag-contact/Cargo.toml
  bin/domain/imag-habit/Cargo.toml
  bin/domain/imag-mail/Cargo.toml
  doc/Makefile
  doc/src/00000.md
  doc/src/09020-changelog.md
  lib/domain/libimagcontact/Cargo.toml
  lib/domain/libimaghabit/Cargo.toml
  lib/entry/libimagentryannotation/Cargo.toml
  lib/entry/libimagentrygps/Cargo.toml
  lib/etc/libimagnotification/Cargo.toml
  lib/etc/libimagutil/Cargo.toml
  scripts/release.sh
Labels: meta/WIP, release/hard-required

#1263 Do not print stats when listing files with matches
  bin/core/imag-grep/src/main.rs
Labels: meta/ready

#1265 Add subcommand "help"
  bin/core/imag/src/main.rs
Labels: meta/ready

#1266 Sort commands alphabetically
  bin/core/imag/src/main.rs
Labels: meta/ready

#1264 Alias subcommand "show" to "list"
  bin/domain/imag-log/src/ui.rs
Labels: meta/ready

#1262 Do not print "Ok" after successful execution
  bin/core/imag-annotate/src/main.rs
  bin/core/imag-edit/src/main.rs
  bin/core/imag-gps/src/main.rs
  bin/core/imag-link/src/main.rs
  bin/core/imag-ref/src/main.rs
  bin/domain/imag-contact/src/main.rs
  bin/domain/imag-habit/src/main.rs
  bin/domain/imag-log/src/main.rs
Labels: meta/ready

#1256 Add TraceIterator::trace_unwrap_exit()
  lib/core/libimagerror/src/iter.rs
Labels: meta/WIP

#1270 License header checker
  .travis.yml
  scripts/license-headers-updated
Labels: kind/infrastructure, meta/ready

#1280 Fix: git dir is not worktree dir
  bin/core/imag-init/src/main.rs
Labels: kind/bug, meta/ready

#1275 Clap features
  bin/core/imag-annotate/Cargo.toml
  bin/core/imag-diagnostics/Cargo.toml
  bin/core/imag-gps/Cargo.toml
  bin/core/imag-grep/Cargo.toml
  bin/core/imag-init/Cargo.toml
  bin/core/imag-link/Cargo.toml
  bin/core/imag-mv/Cargo.toml
  bin/core/imag-ref/Cargo.toml
  bin/core/imag-store/Cargo.toml
  bin/core/imag-tag/Cargo.toml
  bin/core/imag-view/Cargo.toml
  bin/core/imag/Cargo.toml
  bin/domain/imag-bookmark/Cargo.toml
  bin/domain/imag-contact/Cargo.toml
  bin/domain/imag-diary/Cargo.toml
  bin/domain/imag-habit/Cargo.toml
  bin/domain/imag-log/Cargo.toml
  bin/domain/imag-mail/Cargo.toml
  bin/domain/imag-notes/Cargo.toml
  bin/domain/imag-timetrack/Cargo.toml
  bin/domain/imag-todo/Cargo.toml
  lib/core/libimagrt/Cargo.toml
  lib/entry/libimagentryfilter/Cargo.toml
  lib/entry/libimagentrylist/Cargo.toml
  lib/entry/libimagentrytag/Cargo.toml
  lib/etc/libimaginteraction/Cargo.toml
  lib/etc/libimagtimeui/Cargo.toml
Labels: meta/ready, missing/test

#1267 Do not allow linking with entry itself
  bin/core/imag-link/src/main.rs
Labels: meta/ready

#1278 imag-init: fix release build include string path
  bin/core/imag-init/imagrc.toml
  bin/core/imag-init/src/main.rs
Labels: meta/WIP

#1283 imag-timetrack: Add kairos support in "list" subcommand
  bin/domain/imag-timetrack/Cargo.toml
  bin/domain/imag-timetrack/src/list.rs
  bin/domain/imag-timetrack/src/main.rs
  doc/src/09020-changelog.md
Labels: kind/feature, meta/importance/low, meta/ready

#1282 libimagtimetrack: refactor
  bin/domain/imag-timetrack/src/cont.rs
  bin/domain/imag-timetrack/src/day.rs
  bin/domain/imag-timetrack/src/list.rs
  bin/domain/imag-timetrack/src/month.rs
  bin/domain/imag-timetrack/src/stop.rs
  bin/domain/imag-timetrack/src/week.rs
  bin/domain/imag-timetrack/src/year.rs
  lib/domain/libimagtimetrack/src/error.rs
  lib/domain/libimagtimetrack/src/iter/create.rs
  lib/domain/libimagtimetrack/src/iter/get.rs
  lib/domain/libimagtimetrack/src/iter/mod.rs
  lib/domain/libimagtimetrack/src/iter/setendtime.rs
  lib/domain/libimagtimetrack/src/iter/storeid.rs
  lib/domain/libimagtimetrack/src/timetracking.rs
  lib/domain/libimagtimetrack/src/timetrackingstore.rs
Labels: meta/blocker, meta/ready

#1224 Git version in version
  bin/core/imag-annotate/Cargo.toml
  bin/core/imag-annotate/src/main.rs
  bin/core/imag-diagnostics/Cargo.toml
  bin/core/imag-diagnostics/src/main.rs
  bin/core/imag-edit/Cargo.toml
  bin/core/imag-edit/src/main.rs
  bin/core/imag-gps/Cargo.toml
  bin/core/imag-gps/src/main.rs
  bin/core/imag-grep/Cargo.toml
  bin/core/imag-grep/src/main.rs
  bin/core/imag-init/Cargo.toml
  bin/core/imag-link/Cargo.toml
  bin/core/imag-link/src/main.rs
  bin/core/imag-mv/Cargo.toml
  bin/core/imag-mv/src/main.rs
  bin/core/imag-ref/Cargo.toml
  bin/core/imag-ref/src/main.rs
  bin/core/imag-store/Cargo.toml
  bin/core/imag-store/src/main.rs
  bin/core/imag-tag/Cargo.toml
  bin/core/imag-tag/src/main.rs
  bin/core/imag-view/Cargo.toml
  bin/core/imag-view/src/main.rs
  bin/core/imag/Cargo.toml
  bin/core/imag/src/main.rs
  bin/domain/imag-bookmark/Cargo.toml
  bin/domain/imag-bookmark/src/main.rs
  bin/domain/imag-contact/Cargo.toml
  bin/domain/imag-contact/src/main.rs
  bin/domain/imag-diary/Cargo.toml
  bin/domain/imag-diary/src/main.rs
  bin/domain/imag-habit/Cargo.toml
  bin/domain/imag-habit/src/main.rs
  bin/domain/imag-log/Cargo.toml
  bin/domain/imag-log/src/main.rs
  bin/domain/imag-mail/Cargo.toml
  bin/domain/imag-mail/src/main.rs
  bin/domain/imag-notes/Cargo.toml
  bin/domain/imag-notes/src/main.rs
  bin/domain/imag-timetrack/Cargo.toml
  bin/domain/imag-timetrack/src/main.rs
  bin/domain/imag-todo/Cargo.toml
  bin/domain/imag-todo/src/main.rs
  build.rs
  lib/core/libimagrt/src/lib.rs
  lib/core/libimagrt/src/version.rs
Labels: kind/nicetohave, meta/WIP, release/optional

#1293 Reduce number of build-jobs
  .travis.yml
Labels: meta/ready

#1294 Simplify Store debug impl
  lib/core/libimagstore/src/store.rs
Labels: meta/ready

#1285 libimagentryref: Rewrite
  bin/core/imag-ref/Cargo.toml
  bin/core/imag-ref/src/main.rs
  bin/core/imag-ref/src/ui.rs
  bin/domain/imag-contact/Cargo.toml
  bin/domain/imag-contact/src/create.rs
  bin/domain/imag-contact/src/main.rs
  doc/src/05100-lib-entryref.md
  lib/domain/libimagcontact/Cargo.toml
  lib/domain/libimagcontact/src/contact.rs
  lib/domain/libimagcontact/src/error.rs
  lib/domain/libimagcontact/src/lib.rs
  lib/domain/libimagcontact/src/store.rs
  lib/domain/libimagmail/src/error.rs
  lib/domain/libimagmail/src/hasher.rs
  lib/domain/libimagmail/src/lib.rs
  lib/domain/libimagmail/src/mail.rs
  lib/entry/libimagentrymarkdown/Cargo.toml
  lib/entry/libimagentrymarkdown/src/processor.rs
  lib/entry/libimagentryref/Cargo.toml
  lib/entry/libimagentryref/src/error.rs
  lib/entry/libimagentryref/src/flags.rs
  lib/entry/libimagentryref/src/generators/base.rs
  lib/entry/libimagentryref/src/generators/mod.rs
  lib/entry/libimagentryref/src/hasher.rs
  lib/entry/libimagentryref/src/hashers/mod.rs
  lib/entry/libimagentryref/src/hashers/nbytes.rs
  lib/entry/libimagentryref/src/lib.rs
  lib/entry/libimagentryref/src/lister.rs
  lib/entry/libimagentryref/src/reference.rs
  lib/entry/libimagentryref/src/refstore.rs
Labels: kind/refactor, meta/WIP, release/hard-required

#1299 imag-ids: init
  Cargo.toml
  bin/core/imag-ids/Cargo.toml
  bin/core/imag-ids/src/main.rs
  bin/core/imag-store/src/ids.rs
  bin/core/imag-store/src/main.rs
  bin/core/imag-store/src/ui.rs
  doc/src/09020-changelog.md
  scripts/release.sh
Labels: meta/ready

#1298 Remove libimagentrylist
  Cargo.toml
  bin/core/imag-ref/Cargo.toml
  bin/core/imag-ref/src/main.rs
  bin/domain/imag-diary/Cargo.toml
  bin/domain/imag-diary/src/list.rs
  bin/domain/imag-diary/src/main.rs
  bin/domain/imag-habit/Cargo.toml
  bin/domain/imag-habit/src/main.rs
  doc/src/05100-lib-entrylist.md
  doc/src/09020-changelog.md
  imagrc.toml
  lib/entry/libimagentrylist/Cargo.toml
  lib/entry/libimagentrylist/README.md
  lib/entry/libimagentrylist/src/error.rs
  lib/entry/libimagentrylist/src/lib.rs
  lib/entry/libimagentrylist/src/lister.rs
  lib/entry/libimagentrylist/src/listers/core.rs
  lib/entry/libimagentrylist/src/listers/line.rs
  lib/entry/libimagentrylist/src/listers/mod.rs
  lib/entry/libimagentrylist/src/listers/path.rs
  lib/entry/libimagentrylist/src/listers/table.rs
  lib/entry/libimagentryref/Cargo.toml
  lib/entry/libimagentryref/src/lib.rs
  scripts/release.sh
Labels: kind/infrastructure, kind/refactor, meta/ready, release/soft-required

#1302 libimagdiary: Add "isflag" support
  lib/domain/libimagdiary/Cargo.toml
  lib/domain/libimagdiary/src/diary.rs
  lib/domain/libimagdiary/src/entry.rs
  lib/domain/libimagdiary/src/error.rs
  lib/domain/libimagdiary/src/lib.rs
Labels: kind/bug, meta/ready

#1303 Fix order of evaluation
  bin/domain/imag-diary/src/util.rs
Labels: kind/bug, meta/ready

#1304 Use the make_imag_version!() helper
  bin/core/imag-init/Cargo.toml
  bin/core/imag-init/src/main.rs
  bin/core/imag-init/src/ui.rs
Labels: kind/bug, meta/ready

#1305 Use writeln!() instead of write!()
  lib/core/libimagerror/src/trace.rs
Labels: kind/bug, meta/ready

#1306 Minor patches
  bin/core/imag/src/main.rs
  doc/src/09020-changelog.md
  lib/domain/libimagdiary/src/diary.rs
  lib/domain/libimagdiary/src/is_in_diary.rs
Labels: meta/ready

#1308 Fix trace count space width
  lib/core/libimagerror/src/trace.rs
Labels: meta/ready

#1307 Rewrite entry parsing algorithm
  doc/src/09020-changelog.md
  lib/core/libimagstore/Cargo.toml
  lib/core/libimagstore/src/error.rs
  lib/core/libimagstore/src/lib.rs
  lib/core/libimagstore/src/util.rs
Labels: kind/bug, meta/ready

#1310 Update uuid to 0.6
  lib/domain/libimagtodo/Cargo.toml
Labels: meta/ready
